#if MC_VERSION >= 11300

entity.10011 = ender_pearl firework_rocket dragon_fireball

entity.10012 = lightning_bolt 

entity.10013 = slime 

entity.10014 = boat chest_boat

entity.10020 = ender_pearl firework_rocket dragon_fireball experience_orb eye_of_ender experience_bottle spectral_arrow end_crystal

entity.10031 = warden

# Светящиеся глаза мобов
entity.10040 = enderman
entity.10041 = spider cave_spider
entity.10042 = drowned
entity.10043 = zombie zombie_villager husk

# Металлические инструменты и оружие с отражениями
entity.15010 = iron_sword iron_axe iron_pickaxe iron_shovel iron_hoe iron_helmet
entity.15011 = copper_sword copper_axe copper_pickaxe copper_shovel copper_hoe
entity.15012 = golden_sword golden_axe golden_pickaxe golden_shovel golden_hoe

#endif