item.13001=glowstone torch jack_o_lantern lantern campfire shroomlight lava_bucket blaze_rod
item.13002=beacon
item.13003=redstone_torch
item.13004=soul_lantern soul_campfire soul_torch
item.13005=sea_lantern
item.13006=end_rod crying_obsidian end_crystal nether_star
item.13007=sea_pickle
item.13008=conduit
item.13009=ochre_froglight
item.13010=verdant_froglight
item.13011=pearlescent_froglight
item.13012=magma_block
item.13013=copper_bulb exposed_copper_bulb weathered_copper_bulb oxidized_copper_bulb waxed_copper_bulb waxed_exposed_copper_bulb waxed_weathered_copper_bulb waxed_oxidized_copper_bulb
item.15010=iron_sword iron_axe iron_pickaxe iron_shovel iron_hoe iron_spear iron_ingot iron_block iron_bars iron_door iron_trapdoor hopper cauldron iron_nugget iron_helmet
item.15011=copper_sword copper_axe copper_pickaxe copper_shovel copper_hoe copper_spear copper_ingot copper_block copper_nugget polished_andesite polished_diorite polished_diorite_slab polished_diorite_stairs polished_andesite_slab polished_andesite_stairs
item.15012=golden_sword golden_axe golden_pickaxe golden_shovel golden_hoe golden_spear gold_ingot gold_block gold_nugget obsidian gray_concrete white_concrete
